### ISSUE TITLE
Sorry

### ISSUE THREAD

**Issue by windiest** [yaoone/article#14]

**Comment by kaasia** [comment]
知乎观光团~~

**Comment by mrmiywj** [comment]
Hi, 不知道我的答案你看到了没有。
正视这件事的话没有人会怪你的，把以前的错误改正过来就行了。

Anyway，祝以后的路越走越顺利。

**Comment by DeKaiju** [comment]
What happened?what's wrong with you?

**Comment by FlyGoat** [comment]
https://www.zhihu.com/question/42256682/answer/94576758

**Comment by mrmiywj** [comment]
Good Luck.
